---
permalink: audit/audit-messages-and-object-lifecycle.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, log, object lifecycle, ingest, retrieve, delete, s3, swift, timing, ILM, Information lifecycle management, archive node, archive nodes 
summary: 'As mensagens de auditoria são geradas sempre que um objeto é ingerido, recuperado ou excluído. Você pode identificar essas transações no log de auditoria localizando mensagens de auditoria específicas da API (S3 ou Swift).' 
---
= Quando são geradas mensagens de auditoria?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As mensagens de auditoria são geradas sempre que um objeto é ingerido, recuperado ou excluído. Você pode identificar essas transações no log de auditoria localizando mensagens de auditoria específicas da API (S3 ou Swift).

As mensagens de auditoria são vinculadas por meio de identificadores específicos a cada protocolo.

[cols="1a,1a"]
|===
| Protocolo | Código 


 a| 
Ligar S3 operações
 a| 
S3BK (balde), S3KY (chave) ou ambos



 a| 
Ligando as operações Swift
 a| 
WCON (container), WOBJ (objeto), ou ambos



 a| 
Vinculação de operações internas
 a| 
CBID (identificador interno do objeto)

|===


== Calendário das mensagens de auditoria

Devido a fatores como diferenças de tempo entre nós de grade, tamanho do objeto e atrasos na rede, a ordem das mensagens de auditoria geradas pelos diferentes serviços pode variar da mostrada nos exemplos nesta seção.



== Nós de arquivamento

A série de mensagens de auditoria geradas quando um nó de arquivo envia dados de objeto para um sistema de armazenamento de arquivo externo é semelhante à dos nós de armazenamento, exceto que não há mensagem SCMT (Store Object Commit), e as mensagens ATCE (Archive Object Store Begin) e ASCE (Archive Object Store End) são geradas para cada cópia arquivada de dados de objeto.

A série de mensagens de auditoria geradas quando um nó de arquivo recupera dados de objetos de um sistema de armazenamento de arquivos externo é semelhante à dos nós de armazenamento, exceto que as mensagens ARCB (recuperação de objetos de arquivamento iniciada) e ARCE (fim de recuperação de objetos de arquivamento) são geradas para cada cópia recuperada de dados de objetos.

A série de mensagens de auditoria geradas quando um nó de arquivo exclui dados de objetos de um sistema de armazenamento de arquivos externo é semelhante à dos nós de armazenamento, exceto que não há nenhuma mensagem SREM (Object Store Remove) e há uma mensagem AREM (Archive Object Remove) para cada solicitação de exclusão.
