---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: O StorageGRID 11,8 usa a versão 4 da API de gerenciamento do locatário. A versão 4 desconsidera a versão 3; no entanto, as versões 1, 2 e 3 ainda são suportadas. 
---
= Alterações na API de gerenciamento do locatário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID 11,8 usa a versão 4 da API de gerenciamento do locatário. A versão 4 desconsidera a versão 3; no entanto, as versões 1, 2 e 3 ainda são suportadas.


NOTE: Você pode continuar usando versões obsoletas da API de gerenciamento de locatário com o StorageGRID 11,8; no entanto, o suporte para essas versões da API será removido em uma versão futura do StorageGRID. Depois de atualizar para o StorageGRID 11,8, as APIs obsoletas podem ser desativadas usando a `PUT /grid/config/management` API.

Para saber mais, link:../tenant/understanding-tenant-management-api.html["Entenda a API de gerenciamento do locatário"]acesse .



== Novos endpoints para tags de política ILM

Você pode usar os pontos de extremidade da API */org/ilm-policy-taGS* e */org/containers/(bucketName)/ilm-policy-taGS* para executar operações relacionadas às tags de política ILM.
