---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: storagegrid software upgrade 
summary: Use estas instruções para atualizar um sistema StorageGRID para uma nova versão. 
---
= Atualizar o software StorageGRID: Visão geral
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use estas instruções para atualizar um sistema StorageGRID para uma nova versão.



== Sobre estas instruções

Estas instruções descrevem as novidades do StorageGRID 11,8 e fornecem instruções passo a passo para atualizar todos os nós do seu sistema StorageGRID para a nova versão.



== Antes de começar

Revise esses tópicos para saber mais sobre os novos recursos e aprimoramentos no StorageGRID 11,8, determinar se algum recurso foi descontinuado ou removido e descobrir as alterações nas APIs do StorageGRID.

* link:whats-new.html["Novidades do StorageGRID 11,8"]
* link:removed-or-deprecated-features.html["Recursos removidos ou obsoletos"]
* link:changes-to-grid-management-api.html["Alterações na API Grid Management"]
* link:changes-to-tenant-management-api.html["Alterações na API de gerenciamento do locatário"]

