---
permalink: swift/history-of-swift-api-support-in-storagegrid.html 
sidebar: sidebar 
keywords: swift api support history 
summary: Você deve estar ciente das alterações no suporte do sistema StorageGRID para a API REST Swift. 
---
= Histórico do suporte à API Swift no StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente das alterações no suporte do sistema StorageGRID para a API REST Swift.

[cols="1a,3a"]
|===
| Solte | Comentários 


 a| 
11,8
 a| 



 a| 
11,7
 a| 
O suporte para aplicativos cliente Swift foi obsoleto e será removido em uma versão futura.



 a| 
11,6
 a| 
Pequenas alterações editoriais.



 a| 
11,5
 a| 
Consistência fraca removida. A consistência disponível será usada em vez disso.



 a| 
11,4
 a| 
Adicionado suporte para TLS 1,3. Adicionada descrição da inter-relação entre ILM e consistência.



 a| 
11,3
 a| 
Operações PUT Object atualizadas para descrever o impactos das regras de ILM que usam o posicionamento síncrono na ingestão (as opções equilibradas e rigorosas para o comportamento de ingestão). Adicionada descrição das conexões de cliente que usam pontos de extremidade do balanceador de carga ou grupos de alta disponibilidade. As cifras TLS 1,1 não são mais suportadas.



 a| 
11,2
 a| 
Pequenas alterações editoriais ao documento.



 a| 
11,1
 a| 
Adicionado suporte para o uso de HTTP para conexões de cliente Swift para nós de grade. Atualizadas as definições de valores de consistência.



 a| 
11,0
 a| 
Adicionado suporte para 1.000 contentores para cada conta de locatário.



 a| 
10,3
 a| 
Atualizações administrativas e correções do documento. Seções removidas para configurar certificados de servidor personalizados.



 a| 
10,2
 a| 
Suporte inicial da API Swift pelo sistema StorageGRID. A versão atualmente suportada é a API de armazenamento de objetos OpenStack Swift v1.

|===