---
permalink: swift/put-container-consistency-request.html 
sidebar: sidebar 
keywords: put container consistency request 
summary: 'A solicitação de consistência de contentor PUT permite especificar a consistência a ser aplicada às operações executadas em um contentor. Por padrão, novos contentores são criados usando a consistência "read-after-new-write".' 
---
= COLOQUE o pedido de consistência do recipiente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A solicitação de consistência de contentor PUT permite especificar a consistência a ser aplicada às operações executadas em um contentor. Por padrão, novos contentores são criados usando a consistência "Read-after-new-write".



== Pedido

[cols="2a,4a"]
|===
| Solicitar cabeçalho HTTP | Descrição 


| X-Auth-Token  a| 
O token de autenticação Swift para a conta a ser usada para a solicitação.



| consistência x-ntap-sg  a| 
A consistência a aplicar às operações no recipiente. Os seguintes valores são suportados:

*Todos*: Todos os nós recebem os dados imediatamente ou a solicitação falhará.

*Strong-global*: Garante consistência de leitura após gravação para todas as solicitações de clientes em todos os sites.

* Strong-site*: Garante consistência de leitura-após-gravação para todas as solicitações de clientes dentro de um site.

*Read-after-novo-write*: (Padrão) fornece consistência de leitura-após-gravação para novos objetos e eventual consistência para atualizações de objetos. Oferece alta disponibilidade e garantias de proteção de dados. Recomendado para a maioria dos casos.

*Disponível*: Fornece consistência eventual para novos objetos e atualizações de objetos. Para buckets do S3, use somente conforme necessário (por exemplo, para um bucket que contém valores de log raramente lidos, ou para operações HEAD ou GET em chaves que não existem). Não compatível com buckets do FabricPool S3.



| Host  a| 
O nome do host para o qual a solicitação é direcionada.

|===


== Como a consistência e as regras de ILM interagem para afetar a proteção de dados

Tanto a sua escolha de consistência quanto a sua regra ILM afetam a forma como os objetos são protegidos. Essas configurações podem interagir.

Por exemplo, a consistência usada quando um objeto é armazenado afeta o posicionamento inicial dos metadados do objeto, enquanto o comportamento de ingestão selecionado para a regra ILM afeta o posicionamento inicial das cópias do objeto. Como o StorageGRID exige acesso aos metadados de um objeto e aos dados para atender às solicitações do cliente, selecionar níveis de proteção correspondentes para o comportamento de consistência e ingestão pode fornecer melhor proteção de dados iniciais e respostas do sistema mais previsíveis.

Os seguintes comportamentos de ingestão estão disponíveis para regras ILM:

* *Strict*: Todas as cópias especificadas na regra ILM devem ser feitas antes que o sucesso seja devolvido ao cliente.
* *Balanced*: O StorageGRID tenta fazer todas as cópias especificadas na regra ILM no ingest; se isso não for possível, cópias provisórias são feitas e o sucesso é retornado ao cliente. As cópias especificadas na regra ILM são feitas quando possível.
* * Commit duplo*: O StorageGRID faz imediatamente cópias provisórias do objeto e retorna sucesso ao cliente. Cópias especificadas na regra ILM são feitas quando possível.



NOTE: Antes de selecionar o comportamento de ingestão para uma regra ILM, leia a descrição completa dessas configurações nas instruções para gerenciar objetos com gerenciamento do ciclo de vida das informações.



== Exemplo de como a consistência e as regras do ILM podem interagir

Suponha que você tenha uma grade de dois locais com a seguinte regra ILM e a seguinte consistência:

* *Regra ILM*: Crie duas cópias de objeto, uma no local e outra em um local remoto. O comportamento de ingestão estrita é selecionado.
* **: "Strong-global" (metadados de objetos são imediatamente distribuídos para todos os sites.)


Quando um cliente armazena um objeto na grade, o StorageGRID faz cópias de objeto e distribui metadados para ambos os sites antes de retornar sucesso ao cliente.

O objeto é totalmente protegido contra perda no momento da mensagem de ingestão bem-sucedida. Por exemplo, se o local for perdido logo após a ingestão, cópias dos dados do objeto e dos metadados do objeto ainda existem no local remoto. O objeto é totalmente recuperável.

Se você usou a mesma regra ILM e a consistência "strong-site", o cliente pode receber uma mensagem de sucesso depois que os dados do objeto são replicados para o site remoto, mas antes que os metadados do objeto sejam distribuídos lá. Nesse caso, o nível de proteção dos metadados de objetos não corresponde ao nível de proteção dos dados de objeto. Se o site local for perdido logo após a ingestão, os metadados do objeto serão perdidos. O objeto não pode ser recuperado.

A inter-relação entre consistência e regras de ILM pode ser complexa. Contacte a NetApp se necessitar de assistência.



== Exemplo de solicitação

[listing]
----
PUT /v1/28544923908243208806/_Swift container_
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: strong-site
Host: test.com
----


== Resposta

|===
| Cabeçalho HTTP de resposta | Descrição 


 a| 
`Date`
 a| 
A data e a hora da resposta.



 a| 
`Connection`
 a| 
Se a conexão com o servidor está aberta ou fechada.



 a| 
`X-Trans-Id`
 a| 
O identificador de transação exclusivo para a solicitação.



 a| 
`Content-Length`
 a| 
O comprimento do corpo de resposta.

|===


== Exemplo de resposta

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
----