---
permalink: swift/storagegrid-swift-rest-api-operations.html 
sidebar: sidebar 
keywords: swift rest api operations 
summary: Há operações adicionadas à API REST do Swift que são específicas do sistema StorageGRID. 
---
= Operações da API REST do StorageGRID Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Há operações adicionadas à API REST do Swift que são específicas do sistema StorageGRID.



== OBTER solicitação de consistência de contêiner

link:../s3/consistency-controls.html["Valores de consistência"] Forneça um equilíbrio entre a disponibilidade dos objetos e a consistência desses objetos em diferentes nós de storage e locais. A solicitação GET Container Consistency permite que você determine a consistência que está sendo aplicada a um contentor específico.



=== Pedido

[cols="2a,4a"]
|===
| Solicitar cabeçalho HTTP | Descrição 


| X-Auth-Token  a| 
Especifica o token de autenticação Swift para a conta a ser usada para a solicitação.



| consistência x-ntap-sg  a| 
Especifica o tipo de solicitação, onde `true` OBTÉM consistência de contentor e `false` OBTÉM contentor.



| Host  a| 
O nome do host para o qual a solicitação é direcionada.

|===


=== Exemplo de solicitação

[listing]
----
GET /v1/28544923908243208806/Swift container
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: true
Host: test.com
----


=== Resposta

[cols="2a,4a"]
|===
| Cabeçalho HTTP de resposta | Descrição 


| Data  a| 
A data e a hora da resposta.



| Ligação  a| 
Se a conexão com o servidor está aberta ou fechada.



| X-Trans-ID  a| 
O identificador de transação exclusivo para a solicitação.



| Comprimento do conteúdo  a| 
O comprimento do corpo de resposta.



| consistência x-ntap-sg  a| 
A consistência que está sendo aplicada ao recipiente. Os seguintes valores são suportados:

*Todos*: Todos os nós recebem os dados imediatamente ou a solicitação falhará.

*Strong-global*: Garante consistência de leitura após gravação para todas as solicitações de clientes em todos os sites.

* Strong-site*: Garante consistência de leitura-após-gravação para todas as solicitações de clientes dentro de um site.

*Read-after-novo-write*: (Padrão) fornece consistência de leitura-após-gravação para novos objetos e eventual consistência para atualizações de objetos. Oferece alta disponibilidade e garantias de proteção de dados. Recomendado para a maioria dos casos.

*Disponível*: Fornece consistência eventual para novos objetos e atualizações de objetos. Para buckets do S3, use somente conforme necessário (por exemplo, para um bucket que contém valores de log raramente lidos, ou para operações HEAD ou GET em chaves que não existem). Não compatível com buckets do FabricPool S3.

|===


=== Exemplo de resposta

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
x-ntap-sg-consistency: strong-site
----


== COLOQUE o pedido de consistência do recipiente

A solicitação de consistência de contentor PUT permite especificar a consistência a ser aplicada às operações executadas em um contentor. Por padrão, novos contentores são criados usando a consistência "Read-after-new-write".



=== Pedido

[cols="2a,4a"]
|===
| Solicitar cabeçalho HTTP | Descrição 


| X-Auth-Token  a| 
O token de autenticação Swift para a conta a ser usada para a solicitação.



| consistência x-ntap-sg  a| 
A consistência a aplicar às operações no recipiente. Os seguintes valores são suportados:

*Todos*: Todos os nós recebem os dados imediatamente ou a solicitação falhará.

*Strong-global*: Garante consistência de leitura após gravação para todas as solicitações de clientes em todos os sites.

* Strong-site*: Garante consistência de leitura-após-gravação para todas as solicitações de clientes dentro de um site.

*Read-after-novo-write*: (Padrão) fornece consistência de leitura-após-gravação para novos objetos e eventual consistência para atualizações de objetos. Oferece alta disponibilidade e garantias de proteção de dados. Recomendado para a maioria dos casos.

*Disponível*: Fornece consistência eventual para novos objetos e atualizações de objetos. Para buckets do S3, use somente conforme necessário (por exemplo, para um bucket que contém valores de log raramente lidos, ou para operações HEAD ou GET em chaves que não existem). Não compatível com buckets do FabricPool S3.



 a| 
`Host`
 a| 
O nome do host para o qual a solicitação é direcionada.

|===


=== Como a consistência e as regras de ILM interagem para afetar a proteção de dados

Tanto a sua escolha link:../s3/consistency-controls.html["valor de consistência"] quanto a sua regra ILM afetam a forma como os objetos são protegidos. Essas configurações podem interagir.

Por exemplo, a consistência usada quando um objeto é armazenado afeta o posicionamento inicial dos metadados do objeto, enquanto a link:../ilm/what-ilm-rule-is.html#ilm-rule-ingest-behavior["comportamento de ingestão"]regra selecionada para o ILM afeta o posicionamento inicial das cópias do objeto. Como o StorageGRID exige acesso aos metadados de um objeto e aos dados para atender às solicitações do cliente, selecionar níveis de proteção correspondentes para o comportamento de consistência e ingestão pode fornecer melhor proteção de dados iniciais e respostas do sistema mais previsíveis.



=== Exemplo de como a consistência e as regras do ILM podem interagir

Suponha que você tenha uma grade de dois locais com a seguinte regra ILM e a seguinte consistência:

* *Regra ILM*: Crie duas cópias de objeto, uma no local e outra em um local remoto. O comportamento de ingestão estrita é selecionado.
* **: "Strong-global" (metadados de objetos são imediatamente distribuídos para todos os sites.)


Quando um cliente armazena um objeto na grade, o StorageGRID faz cópias de objeto e distribui metadados para ambos os sites antes de retornar sucesso ao cliente.

O objeto é totalmente protegido contra perda no momento da mensagem de ingestão bem-sucedida. Por exemplo, se o local for perdido logo após a ingestão, cópias dos dados do objeto e dos metadados do objeto ainda existem no local remoto. O objeto é totalmente recuperável.

Se você usou a mesma regra ILM e a consistência "strong-site", o cliente pode receber uma mensagem de sucesso depois que os dados do objeto são replicados para o site remoto, mas antes que os metadados do objeto sejam distribuídos lá. Nesse caso, o nível de proteção dos metadados de objetos não corresponde ao nível de proteção dos dados de objeto. Se o site local for perdido logo após a ingestão, os metadados do objeto serão perdidos. O objeto não pode ser recuperado.

A inter-relação entre consistência e regras de ILM pode ser complexa. Contacte a NetApp se necessitar de assistência.



=== Exemplo de solicitação

[listing]
----
PUT /v1/28544923908243208806/_Swift container_
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: strong-site
Host: test.com
----


=== Resposta

[cols="1a,2a"]
|===
| Cabeçalho HTTP de resposta | Descrição 


 a| 
`Date`
 a| 
A data e a hora da resposta.



 a| 
`Connection`
 a| 
Se a conexão com o servidor está aberta ou fechada.



 a| 
`X-Trans-Id`
 a| 
O identificador de transação exclusivo para a solicitação.



 a| 
`Content-Length`
 a| 
O comprimento do corpo de resposta.

|===


=== Exemplo de resposta

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
----