---
permalink: tenant/configuration-xml-for-search-configuration.html 
sidebar: sidebar 
keywords: search integration, configuration xml, metadata notification, container tag, urn 
summary: O serviço de integração de pesquisa é configurado usando um conjunto de regras contidas nas tags <MetadataNotificationConfiguration\> e </MetadataNotificationConfiguration\>. Cada regra especifica os objetos aos quais a regra se aplica e o destino ao qual o StorageGRID deve enviar os metadados desses objetos. 
---
= Configuração XML para integração de pesquisa
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O serviço de integração de pesquisa é configurado usando um conjunto de regras contidas nas `<MetadataNotificationConfiguration>` tags e `</MetadataNotificationConfiguration>` . Cada regra especifica os objetos aos quais a regra se aplica e o destino ao qual o StorageGRID deve enviar os metadados desses objetos.

Os objetos podem ser filtrados no prefixo do nome do objeto. Por exemplo, você pode enviar metadados para objetos com o prefixo `images` para um destino e metadados para objetos com o prefixo `videos` para outro. As configurações que têm prefixos sobrepostos não são válidas e são rejeitadas quando são enviadas. Por exemplo, uma configuração que inclua uma regra para objetos com o prefixo `test` e uma segunda regra para objetos com o prefixo `test2` não é permitida.

Os destinos devem ser especificados usando a URNA de um endpoint StorageGRID que foi criado para o serviço de integração de pesquisa. Esses endpoints referem-se a um índice e tipo definidos em um cluster do Elasticsearch.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
A tabela descreve os elementos no XML de configuração de notificação de metadados.

[cols="2a,3a,1a"]
|===
| Nome | Descrição | Obrigatório 


 a| 
MetadataNotificationConfiguration
 a| 
Tag de contentor para regras usadas para especificar os objetos e o destino para notificações de metadados.

Contém um ou mais elementos de regra.
 a| 
Sim



 a| 
Regra
 a| 
Tag container para uma regra que identifica os objetos cujos metadados devem ser adicionados a um índice especificado.

Regras com prefixos sobrepostos são rejeitadas.

Incluído no elemento MetadataNotificationConfiguration.
 a| 
Sim



 a| 
ID
 a| 
Identificador exclusivo para a regra.

Incluído no elemento regra.
 a| 
Não



 a| 
Estado
 a| 
O estado pode ser "ativado" ou "Desativado". Nenhuma ação é tomada para regras que são desativadas.

Incluído no elemento regra.
 a| 
Sim



 a| 
Prefixo
 a| 
Os objetos que correspondem ao prefixo são afetados pela regra e seus metadados são enviados para o destino especificado.

Para corresponder a todos os objetos, especifique um prefixo vazio.

Incluído no elemento regra.
 a| 
Sim



 a| 
Destino
 a| 
Etiqueta de contentor para o destino de uma regra.

Incluído no elemento regra.
 a| 
Sim



 a| 
Urna
 a| 
URNA do destino onde os metadados do objeto são enviados. Deve ser a URNA de um endpoint StorageGRID com as seguintes propriedades:

* `es` deve ser o terceiro elemento.
* A URNA deve terminar com o índice e digitar onde os metadados são armazenados, no formulário `domain-name/myindex/mytype`.


Os endpoints são configurados usando o Gerenciador do Locatário ou a API de Gerenciamento do Locatário. Eles assumem a seguinte forma:

* `arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


O endpoint deve ser configurado antes que o XML de configuração seja enviado, ou a configuração falhará com um erro 404.

URNA está incluído no elemento destino.
 a| 
Sim

|===
Use o XML de configuração de notificação de metadados de amostra para aprender a construir seu próprio XML.



== Configuração de notificação de metadados que se aplica a todos os objetos

Neste exemplo, metadados de objetos para todos os objetos são enviados para o mesmo destino.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix></Prefix>
        <Destination>
           <Urn>urn:myes:es:::sgws-notifications/test1/all</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----


== Configuração de notificação de metadados com duas regras

Neste exemplo, metadados de objetos para objetos que correspondem ao prefixo `/images` são enviados para um destino, enquanto metadados de objetos para objetos que correspondem ao prefixo `/videos` são enviados para um segundo destino.

[listing]
----

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Images-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/images</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/es-domain/graphics/imagetype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Videos-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/videos</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-west-1:22222222:domain/es-domain/graphics/videotype</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.Informações relacionadas
link:../s3/index.html["USE A API REST DO S3"]

link:object-metadata-included-in-metadata-notifications.html["Metadados de objetos incluídos nas notificações de metadados"]

link:json-generated-by-search-integration-service.html["JSON gerado pelo serviço de integração de pesquisa"]

link:configuring-search-integration-service.html["Configurar o serviço de integração de pesquisa"]
