---
permalink: tenant/object-metadata-included-in-metadata-notifications.html 
sidebar: sidebar 
keywords: object metadata notification 
summary: A tabela lista todos os campos que estão incluídos no documento JSON que é enviado para o endpoint de destino quando a integração de pesquisa está ativada. 
---
= Metadados de objetos incluídos nas notificações de metadados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A tabela lista todos os campos que estão incluídos no documento JSON que é enviado para o endpoint de destino quando a integração de pesquisa está ativada.

O nome do documento inclui o nome do intervalo, o nome do objeto e a ID da versão, se presente.

[cols="1a,2a"]
|===
| Tipo | Nome e descrição do item 


 a| 
Informações sobre o balde e o objeto
 a| 
`bucket`: Nome do balde



 a| 
`key`: Nome da chave do objeto



 a| 
`versionID`: Versão do objeto, para objetos em buckets versionados



 a| 
`region`: Região do balde, por exemplo `us-east-1`



 a| 
Metadados do sistema
 a| 
`size`: Tamanho do objeto (em bytes) como visível para um cliente HTTP



 a| 
`md5`: Hash de objeto



 a| 
Metadados do usuário
 a| 
`metadata`: Todos os metadados de usuário para o objeto, como pares de chave-valor

`key:value`



 a| 
Tags
 a| 
`tags`: Todas as tags de objeto definidas para o objeto, como pares chave-valor

`key:value`

|===

NOTE: Para tags e metadados de usuários, o StorageGRID passa datas e números para o Elasticsearch como strings ou como notificações de eventos do S3. Para configurar o Elasticsearch para interpretar essas strings como datas ou números, siga as instruções do Elasticsearch para mapeamento de campos dinâmicos e para os formatos de data de mapeamento. Você deve ativar os mapeamentos de campo dinâmicos no índice antes de configurar o serviço de integração de pesquisa. Depois que um documento é indexado, você não pode editar os tipos de campo do documento no índice.
