---
permalink: rhel/installing-linux.html 
sidebar: sidebar 
keywords: how to install on red hat linux 
summary: Você deve instalar o StorageGRID em todos os hosts de grade do Red Hat Enterprise Linux. Para obter uma lista de versões suportadas, utilize a ferramenta de Matriz de interoperabilidade do NetApp. 
---
= Instale o Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve instalar o StorageGRID em todos os hosts de grade do Red Hat Enterprise Linux. Para obter uma lista de versões suportadas, utilize a ferramenta de Matriz de interoperabilidade do NetApp.


NOTE: Certifique-se de que o seu sistema operativo está atualizado para o kernel Linux 4,15 ou superior.

.Passos
. Instale o Linux em todos os hosts de grade física ou virtual de acordo com as instruções do distribuidor ou seu procedimento padrão.
+

NOTE: Se você estiver usando o instalador padrão do Linux, o NetApp recomenda selecionar a configuração do software "nó de computação", se disponível, ou o ambiente base "instalação mínima". Não instale nenhum ambiente de desktop gráfico.

. Certifique-se de que todos os hosts tenham acesso aos repositórios de pacotes, incluindo o canal Extras.
+
Você pode precisar desses pacotes adicionais mais tarde neste procedimento de instalação.

. Se a troca estiver ativada:
+
.. Execute o seguinte comando: `$ sudo swapoff --all`
.. Remova todas as entradas de troca de `/etc/fstab` para persistir as configurações.


+

NOTE: A falha ao desativar completamente a troca pode reduzir drasticamente o desempenho.


