---
permalink: monitor/logs-files-reference.html 
sidebar: sidebar 
keywords: log, logs, log files 
summary: O StorageGRID fornece logs que são usados para capturar eventos, mensagens de diagnóstico e condições de erro. Você pode ser solicitado a coletar arquivos de log e encaminhá-los para o suporte técnico para ajudar na solução de problemas. 
---
= Referência de ficheiros de registo: Visão geral
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID fornece logs que são usados para capturar eventos, mensagens de diagnóstico e condições de erro. Você pode ser solicitado a coletar arquivos de log e encaminhá-los para o suporte técnico para ajudar na solução de problemas.

Os logs são categorizados da seguinte forma:

* link:storagegrid-software-logs.html["Registos do software StorageGRID"]
* link:deployment-and-maintenance-logs.html["Logs de implantação e manutenção"]
* link:logs-for-third-party-software.html["Logs para software de terceiros"]
* link:about-bycast-log.html["Sobre o bycast.log"]



NOTE: Os detalhes fornecidos para cada tipo de log são apenas para referência. Os registos destinam-se à resolução de problemas avançada por suporte técnico. Técnicas avançadas que envolvem a reconstrução do histórico de problemas usando os logs de auditoria e os arquivos de log do aplicativo estão além do escopo dessas instruções.



== Aceder aos registos

Para acessar os logs, você pode link:collecting-log-files-and-system-data.html["colete arquivos de log e dados do sistema"] de um ou mais nós como um único arquivo de log. Ou, se o nó Admin principal não estiver disponível ou não conseguir alcançar um nó específico, você poderá acessar arquivos de log individuais para cada nó de grade da seguinte forma:

. Introduza o seguinte comando: `ssh admin@grid_node_IP`
. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
. Digite o seguinte comando para mudar para root: `su -`
. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.




== Categorias de ficheiros de registo

O arquivo de log do StorageGRID contém os logs descritos para cada categoria e arquivos adicionais que contêm métricas e saída de comando de depuração.

[cols="1a,3a"]
|===
| Localização do arquivo | Descrição 


| auditoria  a| 
Mensagens de auditoria geradas durante a operação normal do sistema.



| base-os-logs  a| 
Informações básicas do sistema operacional, incluindo versões de imagem StorageGRID.



| pacotes  a| 
Informações de configuração global (pacotes).



| cassandra  a| 
Informações do banco de dados Cassandra e Registros de reparo do Reaper.



| ce  a| 
Informações de VCSs sobre o nó atual e as informações de grupo EC por ID de perfil.



| grelha  a| 
Logs gerais de grade incluindo debug (`bycast.log`) e `servermanager` logs.



| grid.xml  a| 
Arquivo de configuração de grade compartilhado em todos os nós.



| grupos  a| 
A alta disponibilidade agrupa métricas e logs.



| instale  a| 
`Gdu-server` e instalar logs.



| lumberjack.log  a| 
Depurar mensagens relacionadas à coleção de logs.



| Lambda-árbitro  a| 
Logs relacionados à solicitação de proxy S3 Select.



| Métricas  a| 
Logs de serviço para Grafana, Jaeger, nó exportador e Prometheus.



| miscd  a| 
Registos de acesso e erro incorretos.



| mysql  a| 
A configuração do banco de dados MariaDB e logs relacionados.



| rede  a| 
Logs gerados por scripts relacionados à rede e pelo serviço Dynip.



| nginx  a| 
Arquivos e logs de configuração de federação de grade e balanceador de carga. Também inclui logs de tráfego do Grid Manager e do Tenant Manager.



| nginx-gw  a| 
Arquivos e logs de configuração de federação de grade e balanceador de carga.



| ntp  a| 
Ficheiro de configuração NTP e registos.



| so  a| 
Arquivo de estado de nó e grade, incluindo serviços `pid`.



| outros  a| 
Arquivos de log sob `/var/local/log` que não são coletados em outras pastas.



| perf  a| 
Informações de desempenho para CPU, rede e e/S de disco



| prometheus-data  a| 
Métricas atuais do Prometheus, se a coleção de logs incluir dados do Prometheus.



| provisionamento  a| 
Logs relacionados ao processo de provisionamento de grade.



| jangada  a| 
Registros do cluster de jangada usados em serviços de plataforma.



| ssh  a| 
Logs relacionados à configuração e serviço SSH.



| snmp  a| 
Configuração do agente SNMP e listas de permissão/negação de alarme usadas para enviar notificações SNMP.



| sockets-dados  a| 
Dados de sockets para depuração de rede.



| system-commands.txt  a| 
Saída de comandos StorageGRID Container. Contém informações do sistema, como utilização de rede e disco.

|===